branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: Planet Mapper
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
