export interface Planet {
        pl_hostname: string;
        pl_letter: string;
        pl_name: string;
        pl_discmethod: string;
        pl_controvflag: number;
        pl_pnum: number;
        pl_orbper: number;
        pl_orbpererr1: number;
        pl_orbpererr2: number;
        pl_orbperlim: number | null;
        pl_orbpern: number | null;
        pl_orbsmax: number | null;
        pl_orbsmaxerr1: number | null;
        pl_orbsmaxerr2: number | null;
        pl_orbsmaxlim: number | null;
        pl_orbsmaxn: number | null;
        pl_orbeccen: number | null;
        pl_orbeccenerr1: number | null;
        pl_orbeccenerr2: number | null;
        pl_orbeccenlim: number | null;
        pl_orbeccenn: number | null;
        pl_orbincl: number | null;
        pl_orbinclerr1: number | null;
        pl_orbinclerr2: number | null;
        pl_orbincllim: number | null;
        pl_orbincln: number | null;
        pl_bmassj: number | null;
        pl_bmassjerr1: number | null;
        pl_bmassjerr2: number | null;
        pl_bmassjlim: number | null;
        pl_bmassn: number | null;
        pl_bmassprov: string | null;
        pl_radj: number | null;
        pl_radjerr1: number | null;
        pl_radjerr2: number | null;
        pl_radjlim: number | null | null;
        pl_radn: number | null;
        pl_dens: number | null;
        pl_denserr1: number | null;
        pl_denserr2: number | null;
        pl_denslim: number | null;
        pl_densn: number | null;
        pl_ttvflag: number | null;
        pl_kepflag: number | null;
        pl_k2flag: number | null;
        ra_str: string;
        dec_str: string;
        ra: number | null;
        st_raerr: number | null;
        dec: number | null;
        st_decerr: number | null;
        st_posn: number | null;
        st_dist: number | null;
        st_disterr1: number | null;
        st_disterr2: number | null;
        st_distlim: number | null;
        st_distn: number | null;
        st_optmag: number | null;
        st_optmagerr: number | null;
        st_optmaglim: number | null;
        st_optband: string | null;
        gaia_gmag: number | null;
        gaia_gmagerr: number | null;
        gaia_gmaglim: number | null | null;
        st_teff: number | null;
        st_tefferr1: number | null;
        st_tefferr2: number | null;
        st_tefflim: number | null;
        st_teffn: number | null;
        st_mass: number | null;
        st_masserr1: number | null;
        st_masserr2: number | null;
        st_masslim: number | null;
        st_massn: number | null;
        st_rad: number | null;
        st_raderr1: number | null;
        st_raderr2: number | null;
        st_radlim: number | null;
        st_radn: number | null;
        pl_nnotes: number | null;
        rowupdate: string;
        pl_facility: string;
}

